#!/usr/bin/env python
# -*- coding: us-ascii -*-
# generated by wxGlade 0.6.3 on Sun Aug  2 14:05:43 2009

import wx



class AboutDialog(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: .__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        Img = wx.Image('icon.png', wx.BITMAP_TYPE_PNG)
        bitmap = wx.BitmapFromImage(Img)
        self.image1 = wx.StaticBitmap(self,bitmap=bitmap)
        self.label_0 = wx.StaticText(self, -1, "Virtual Femtolab v0.8")
        self.label_1 = wx.StaticText(self, -1, 'Application that calculates the propagation effects in an ultrafast pulsed laser beam')
        self.link_1 = wx.HyperlinkCtrl(self, -1, "Project website at IFIMUP-IN",'http://faraday.fc.up.pt/ifimup-in/research-areas/ultrafast-lasers-and-magnetodynamics-spectroscopies-research/virtual-femtolab')
        self.link_2 = wx.HyperlinkCtrl(self, -1, "Source code at GitHub",'http://www.github.com/fsilva/Virtual-Femtolab/')
        self.button_1 = wx.Button(self, -1, "Ok")

        self.__set_properties()
        self.__do_layout()
        
        self.Bind(wx.EVT_HYPERLINK, self.link_click, self.link_2)
        self.Bind(wx.EVT_HYPERLINK, self.link_click, self.link_1)
        self.Bind(wx.EVT_BUTTON, self.ok_click, self.button_1)
        # end wxGlade



    def __set_properties(self):
        # begin wxGlade: .__set_properties
        self.SetTitle("About")
        self.SetBackgroundColour(wx.SystemSettings.GetColour(wx.SYS_COLOUR_BTNFACE))
        # end wxGlade
        
        

    def __do_layout(self):
        # begin wxGlade: .__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_1.Add(self.image1,  0, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 5)
        sizer_1.Add(self.label_0,  0, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 5)
        sizer_1.Add(self.label_1,  0, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 5)
        sizer_1.Add(self.link_1,   0, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 5)
        sizer_1.Add(self.link_2,   0, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 5)
        sizer_1.Add(self.button_1, 0, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL, 10)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        # end wxGlade
        
        
        
    def link_click(self,event):
        import webbrowser
        webbrowser.open(event.URL)
        



    def ok_click(self, event): # wxGlade: .<event_handler>
        self.Close()
        event.Skip()

# end of class


