#!/usr/bin/env python
# -*- coding: us-ascii -*-
# generated by wxGlade 0.6.3 on Wed Sep  9 17:51:28 2009

import wx
import wx.grid

# begin wxGlade: extracode
# end wxGlade



class EstimativesDialog(wx.Frame):
    def __init__(self, cleanup_function=None, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.sizer_4_staticbox = wx.StaticBox(self, -1, "Plasma Formation Parameters")
        self.sizer_3_staticbox = wx.StaticBox(self, -1, "Material Parameters")
        self.label_1 = wx.StaticText(self, -1, "n", style=wx.ALIGN_CENTRE)
        self.text_n = wx.TextCtrl(self, -1, "1", style=wx.TE_PROCESS_ENTER|wx.TE_RIGHT)
        self.label_2 = wx.StaticText(self, -1, "GVD", style=wx.ALIGN_CENTRE)
        self.text_gvd = wx.TextCtrl(self, -1, "20")
        self.label_9 = wx.StaticText(self, -1, "fs**2/m")
        self.label_3 = wx.StaticText(self, -1, "n2", style=wx.ALIGN_CENTRE)
        self.text_n2 = wx.TextCtrl(self, -1, "1")
        self.label_10 = wx.StaticText(self, -1, "m**2/W")
        self.label_4 = wx.StaticText(self, -1, "K", style=wx.ALIGN_CENTRE)
        self.text_k = wx.TextCtrl(self, -1, "8")
        self.label_5 = wx.StaticText(self, -1, "rho", style=wx.ALIGN_CENTRE)
        self.text_rho = wx.TextCtrl(self, -1, "1")
        self.label_11 = wx.StaticText(self, -1, "m**-3", style=wx.ALIGN_CENTRE)
        self.label_6 = wx.StaticText(self, -1, "rho critical", style=wx.ALIGN_CENTRE)
        self.text_rho_c = wx.TextCtrl(self, -1, "1")
        self.label_11_copy = wx.StaticText(self, -1, "m**-3", style=wx.ALIGN_CENTRE)
        self.label_7 = wx.StaticText(self, -1, "rho atomic", style=wx.ALIGN_CENTRE)
        self.text_rho_at = wx.TextCtrl(self, -1, "1")
        self.label_11_copy_1 = wx.StaticText(self, -1, "m**-3", style=wx.ALIGN_CENTRE)
        self.label_8 = wx.StaticText(self, -1, "sigmaK", style=wx.ALIGN_CENTRE)
        self.text_sigmaK = wx.TextCtrl(self, -1, "1")
        self.label_12 = wx.StaticText(self, -1, "m**2K/W**K/s**-1(TODO)")
        self.grid_1 = wx.grid.Grid(self, -1, size=(1, 1))

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_TEXT, self.text_changed, self.text_n)
        self.Bind(wx.EVT_TEXT, self.text_changed, self.text_gvd)
        self.Bind(wx.EVT_TEXT, self.text_changed, self.text_n2)
        self.Bind(wx.EVT_TEXT, self.text_changed, self.text_k)
        self.Bind(wx.EVT_TEXT, self.text_changed, self.text_rho)
        self.Bind(wx.EVT_TEXT, self.text_changed, self.text_rho_c)
        self.Bind(wx.EVT_TEXT, self.text_changed, self.text_rho_at)
        self.Bind(wx.EVT_TEXT, self.text_changed, self.text_sigmaK)
        
        self.Bind(wx.EVT_CLOSE, self.on_close)
        self.cleanup_function = cleanup_function
        # end 

    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle("Nonlinear Optics Propagation Estimatives")
        self.grid_1.CreateGrid(9, 3)
        self.grid_1.SetRowLabelSize(0)
        self.grid_1.SetColLabelSize(0)
        self.grid_1.EnableEditing(0)
        self.grid_1.EnableDragColSize(0)
        self.grid_1.EnableDragRowSize(0)
        self.grid_1.EnableDragGridSize(0)
        self.grid_1.SetMinSize((250, 200))
        
        
        self.grid_1.SetDefaultCellFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.NORMAL, wx.FONTWEIGHT_NORMAL))
        self.grid_1.SetCellValue(0,0,'Defocusing distance')
        self.grid_1.SetCellValue(1,0,'GVD distance')
        self.grid_1.SetCellValue(2,0,'Self focusing distance')
        self.grid_1.SetCellValue(3,0,'Beam Collapse distance')
        self.grid_1.SetCellValue(4,0,'Plasma defocusing distance')
        self.grid_1.SetCellValue(5,0,'MPA absorption distance')
        self.grid_1.SetCellValue(6,0,'MPA absorption coefficient')
        self.grid_1.SetCellValue(7,0,'Critical Power')
        self.grid_1.SetCellValue(8,0,'SPM estimative')
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_4 = wx.StaticBoxSizer(self.sizer_4_staticbox, wx.VERTICAL)
        sizer_12 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_11 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_10 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_9 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_8 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3 = wx.StaticBoxSizer(self.sizer_3_staticbox, wx.VERTICAL)
        sizer_7 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_6 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_5 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_5.Add(self.label_1, 1, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 5)
        sizer_5.Add(self.text_n, 0, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 5)
        sizer_5.Add((20, 1), 1, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 5)
        sizer_3.Add(sizer_5, 1, wx.EXPAND, 0)
        sizer_6.Add(self.label_2, 1, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 5)
        sizer_6.Add(self.text_gvd, 0, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 5)
        sizer_6.Add(self.label_9, 1, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 5)
        sizer_3.Add(sizer_6, 1, wx.EXPAND, 0)
        sizer_7.Add(self.label_3, 1, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 5)
        sizer_7.Add(self.text_n2, 0, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 5)
        sizer_7.Add(self.label_10, 1, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 5)
        sizer_3.Add(sizer_7, 1, wx.EXPAND, 0)
        sizer_2.Add(sizer_3, 1, wx.EXPAND, 0)
        sizer_8.Add(self.label_4, 1, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 5)
        sizer_8.Add(self.text_k, 0, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 5)
        sizer_8.Add((20, 1), 1, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 5)
        sizer_4.Add(sizer_8, 1, wx.EXPAND, 0)
        sizer_9.Add(self.label_5, 1, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 5)
        sizer_9.Add(self.text_rho, 0, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 5)
        sizer_9.Add(self.label_11, 1, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 5)
        sizer_4.Add(sizer_9, 1, wx.EXPAND, 0)
        sizer_10.Add(self.label_6, 1, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 5)
        sizer_10.Add(self.text_rho_c, 0, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 5)
        sizer_10.Add(self.label_11_copy, 1, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 5)
        sizer_4.Add(sizer_10, 1, wx.EXPAND, 0)
        sizer_11.Add(self.label_7, 1, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 5)
        sizer_11.Add(self.text_rho_at, 0, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 5)
        sizer_11.Add(self.label_11_copy_1, 1, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 5)
        sizer_4.Add(sizer_11, 1, wx.EXPAND, 0)
        sizer_12.Add(self.label_8, 1, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 5)
        sizer_12.Add(self.text_sigmaK, 0, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 5)
        sizer_12.Add(self.label_12, 0, 0, 0)
        sizer_4.Add(sizer_12, 1, wx.EXPAND, 0)
        sizer_2.Add(sizer_4, 1, wx.EXPAND, 0)
        sizer_1.Add(sizer_2, 1, wx.EXPAND, 0)
        sizer_1.Add(self.grid_1, 1, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 5)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        # end wxGlade
    
    def set_pulseBeam(self,pulseBeam):
        self.pulseBeam = pulseBeam

        
    def update_estimatives(self):
        self.read_parameters()
        
        self.update_grid_value_meters(0, self.pulseBeam.calc_diffraction_distance(self.n))
        self.update_grid_value_meters(1, self.pulseBeam.calc_gvd_distance(self.gvd))
        self.update_grid_value_meters(2, self.pulseBeam.calc_selffocusing_distance(self.n,self.n2))
        self.update_grid_value_meters(3, self.pulseBeam.calc_collapse_distance(self.n,self.n2))
        self.update_grid_value_meters(4, self.pulseBeam.calc_plasmadefocusing_distance(self.n,self.rho,self.rho_c,self.rho_at))
        att,dist = self.pulseBeam.calc_MPA_attenuation_and_distance(self.K,self.sigmaK,self.rho_at)
        self.grid_1.SetCellValue(5,1,'%3.5e'%(att))
        self.update_grid_value_meters(6, dist)
        self.grid_1.SetCellValue(7,1,'%3.5e'%(self.pulseBeam.calc_critical_power(self.n,self.n2)))
        self.grid_1.SetCellValue(7,2,'W')
        
        self.grid_1.AutoSize()
        
        
    def update_grid_value_meters(self, line, distance):
        if(distance >= 1):
            self.grid_1.SetCellValue(line,1,'%4.5f'%(distance))
            self.grid_1.SetCellValue(line,2,'m')
        elif(distance >= 0.001):
            self.grid_1.SetCellValue(line,1,'%3.5f'%(distance*1000))
            self.grid_1.SetCellValue(line,2,'mm')
        else:
            self.grid_1.SetCellValue(line,1,'%3.5e'%(distance*1e6))
            self.grid_1.SetCellValue(line,2,'um')
        
        
    
    def read_parameters(self):
        # Problem: eval is a possible security hole. An user could just type malicious code in the text boxes. But then again, who would do that? why not open the python interpreter?
        try: 
            self.n = eval(self.text_n.GetValue())
            self.gvd = eval(self.text_gvd.GetValue())
            self.n2 = eval(self.text_n2.GetValue())
            self.K = eval(self.text_k.GetValue())
            self.rho = eval(self.text_rho.GetValue())
            self.rho_c = eval(self.text_rho_c.GetValue())
            self.rho_at = eval(self.text_rho_at.GetValue())
            self.sigmaK = eval(self.text_sigmaK.GetValue())
        except SyntaxError as exception:
            print 'Erro when converting text to real number: ', exception.args[1][3]

    def text_changed(self, event): # wxGlade: .<event_handler>
        self.update_estimatives()
        event.Skip()
        
    def on_close(self, event):
        self.cleanup_function()
        self.Destroy()
        del self

# end of class MyFrame


if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_1 = MyFrame(None, -1, "")
    app.SetTopWindow(frame_1)
    frame_1.Show()
    app.MainLoop()
